include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

before_script:
  - docker-compose up -d

services:
  - "$DIND_IMAGE"

variables:
  DOCKER_HOST: tcp://docker:2375/
